### PR TITLE
add new meme for Create PR

### PR DESCRIPTION
**Pull request by pershin-daniil**
image

### CODE REVIEW

**Comment by ADTC** [comment]
I think you need to put the image inside the `images` folder and link it with a relative location. See the rest of the images, how they are linked. 🙂 (Also, use a meaningful file name.)

image

**Comment by pershin-daniil** [comment]
@ADTC done)

**Comment by ADTC** [comment]
I'd like to suggest adding for "Create PR": `i-have-no-idea-what-im-doing.png` _(BTW: maybe better if we convert all images to JPG actually)_

i-have-no-idea-what-im-doing

**Comment by ADTC** [comment]
Why closed?

**Comment by pershin-daniil** [comment]
Because it's too much for one picture

**Pull request closed without merging**
